### ISSUE TITLE
Documentation: integration with netlify

### ISSUE THREAD

**Issue by vielmetti** [blenderskool/pencil#52]
It would be super-helpful for the documentation to walk through a simple example of deploying a docbook web site using Netlify.

**Comment by grahamc** [comment]
There are confusingly _two_ docbooks now, but I'd be interested in this docbook: https://docbook.org

**Comment by blenderskool** [comment]
Documentation is still under development. You can check out some basic deployment instructions on https://docbook.netlify.com/deploy/
