### ISSUE TITLE
DocBook's name collides with a formally specified documentation tool

### ISSUE THREAD

**Issue by grahamc** [blenderskool/pencil#53]
Hello,

I'm guessing you know already, but just wanted to open an issue just in case.

DocBook (https://docbook.org) is a schema (https://docbook.org/schemas/) by OASIS (https://www.oasis-open.org/), and I'm not sure it is okay to create another publishing tool of the same name. I couldn't find any specific mention (also, I'm not a lawyer) but I suspect OASIS has a copyright to the name DocBook.

I've cc'd @ndw who does a lot with DocBook and its specification.

**Comment by blenderskool** [comment]
Ah! Never thought that there will be discrepancies in naming this project.

As both are different in what they do, **I will rename this project to a different name**. It's going to be a hard time for me!

**Comment by grahamc** [comment]
Thank you so much, Akash!

**Comment by blenderskool** [comment]
Closed via #54

**Comment by grahamc** [comment]
Thank you again for how you've handled this, I really appreciate it.
